### ISSUE TITLE
description and Text columns show the same

### ISSUE THREAD

**Issue by biohazardxxx** [Hanse/maconomy#11]
Hi,

when I run a show command the Description (entryText) and Text (taskDescription) columns show the same. 
Also text stated within the "add" function does not appear in the "Remarks" text box at the maconomy UI and in the table out:
`node .\cli.js add 9135 412 1.5 2019-04-30 TEST`
![image](https://user-images.githubusercontent.com/1370362/56789735-ebfd9a80-6802-11e9-9c7b-986d4ddf7b19.png)

Not sure if that is a maconomy install specific thing?
However looking first on the show, I am after ...daily.map(day => day.description), as this gives the value from the remarks box per day.
However my js skills aren't sufficient yet to change the code. Tried the below within the show function around line 328 but it gives a destroyed table
```
    table.push([
      projectId,
      task,
      taskDescription,
      ...daily.map(day => (day.hours === '0.00' ? '' : day.hours)),
      ...daily.map(day => day.description),
      fromTimeSheetLineId(key)
    ]);
```
Any hint?

**Comment by biohazardxxx** [comment]
I figured out that this differs by project some need the text in EntryText and for others DailyDescription.
I am ok closing this as I think to implement to show DailyDescription might not fit everyone's need

**Comment by hanse** [comment]
Using our install `Task Description` and `Text` in the Maconomy GUI is what is shown in the table for description and text.

I know that there is some issues with populating these fields
![Screenshot 2019-05-09 at 21 08 28](https://user-images.githubusercontent.com/20185/57479846-b050df00-729e-11e9-8b47-a2c08cd19f09.png). 
and I used to do them manually afterwards.
